const allModelName = [
  'topazlabs',
  'clipdrop',
  'commanda',
  'nvidia',
  'vllm',
  'pixverse',
  'infinigence',
  'yandex',
  'flora',
  'rsshub',
  'baichuan',
  'lightricks',
  'greptile',
  'aya',
  'mistral',
  'notebooklm',
  'ollama',
  'searchapi',
  'deepseek',
  'n8n',
  'automatic',
  'colab',
  'monica',
  'vidu',
  'stepfun',
  'doc2x',
  'glif',
  'cursor',
  'stability',
  'search1api',
  'ppio',
  'codegeex',
  'dreammachine',
  'cloudflare',
  'novita',
  'fireworks',
  'adobefirefly',
  'google',
  'volcengine',
  'langsmith',
  'statecloud',
  'notion',
  'cerebras',
  'tencent',
  'openwebui',
  'kimi',
  'phidata',
  'fal',
  'meta',
  'tii',
  'bedrock',
  'railway',
  'poe',
  'upstage',
  'midjourney',
  'cogview',
  'comfyui',
  'spark',
  'aistudio',
  'deepmind',
  'sambanova',
  'cogvideo',
  'dify',
  'aws',
  'crewai',
  'bytedance',
  'gemini',
  'groq',
  'baiducloud',
  'make',
  'anthropic',
  'iflytekcloud',
  'pika',
  'xuanyuan',
  'openchat',
  'goose',
  'myshell',
  'azureai',
  'perplexity',
  'openai',
  'claude',
  'alibabacloud',
  'antgroup',
  'hunyuan',
  'together',
  'vectorizerai',
  'vertexai',
  'wenxin',
  'openrouter',
  'ai21',
  'moonshot',
  'livekit',
  'sync',
  'llava',
  'langchain',
  'llamaindex',
  'jina',
  'deepinfra',
  'huggingface',
  'civitai',
  'baai',
  'ai360',
  'aimass',
  'copilot',
  'xai',
  'luma',
  'yuanbao',
  'bing',
  'siliconcloud',
  'tripo',
  'qwen',
  'langfuse',
  'chatglm',
  'deepai',
  'tiangong',
  'internlm',
  'dbrx',
  'exa',
  'ideogram',
  'zeabur',
  'github',
  'githubcopilot',
  'zeroone',
  'cline',
  'udio',
  'zhipu',
  'tencentcloud',
  'gradio',
  'kling',
  'adobe',
  'magic',
  'qingyan',
  'xinference',
  'kera',
  'coze',
  'modelscope',
  'replicate',
  'flowith',
  'doubao',
  'runway',
  'workersai',
  'microsoft',
  'nova',
  'replit',
  'sensenova',
  'palm',
  'rwkv',
  'langgraph',
  'mcp',
  'minimax',
  'hedra',
  'unstructured',
  'baidu',
  'higress',
  'haiper',
  'hailuo',
  'fishaudio',
  'lobehub',
  'azure',
  'gemma',
  'coqui',
  'dalle',
  'flux',
  'manus',
  'cohere',
  'docsearch',
  'lambda',
  'lmstudio',
  'alibaba',
  'suno',
  'v0',
  'yi',
  'viggle',
  'grok',
  'recraft',
  'vercel',
  'giteeai',
  'pollinations',
];

export function matchModelString(string = '', modelArray = allModelName) {
  const parts = string.split('/');

  // 尝试匹配第一部分
  if (parts[0]) {
    const firstPart = parts[0];
    // 精确匹配
    if (modelArray.includes(firstPart)) {
      return firstPart;
    }
    // 模糊匹配
    for (let i = 0; i < modelArray.length; i++) {
      if (firstPart.toLowerCase().includes(modelArray[i])) {
        return modelArray[i];
      }
    }
  }

  // 如果有第二部分，尝试匹配第二部分
  if (parts[1]) {
    const secondPart = parts[1];
    // 精确匹配
    if (modelArray.includes(secondPart)) {
      return secondPart;
    }
    // 模糊匹配
    for (let i = 0; i < modelArray.length; i++) {
      if (secondPart.toLowerCase().includes(modelArray[i])) {
        return modelArray[i];
      }
    }
  }

  return null;
}
